# Generated by Django 2.2.6 on 2019-10-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serathonapp', '0003_auto_20191026_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
