# Generated by Django 2.2.6 on 2019-10-26 23:01

import chatterbot.conversation
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serathonapp', '0004_profile_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time that the statement was created at.')),
                ('persona', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('search_text', models.TextField()),
                ('conversation', models.TextField()),
                ('in_response_to', models.TextField()),
                ('search_in_response_to', models.TextField()),
                ('tags', models.ManyToManyField(related_name='statements', to='serathonapp.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, chatterbot.conversation.StatementMixin),
        ),
    ]
